export enum ActionType {
  STORE_UNLOCK = 'STORE_UNLOCK',
  STORE_LOCK = 'STORE_LOCK',

  KEY_GENERATE = 'KEY_GENERATE',
  KEY_SELECT = 'KEY_SELECT',
  KEY_IMPORT = 'KEY_IMPORT',
  KEY_EXPORT = 'KEY_EXPORT',
  KEY_REMOVE = 'KEY_REMOVE',
}
